export default `
unbindall
bind TAB "+showscores"
bind ESCAPE "cancelselect"
bind SPACE "+jump"
bind , "buyammo1"
bind . "buyammo2"
bind 0 "slot10"
bind 1 "slot1"
bind 2 "slot2"
bind 3 "slot3"
bind 4 "slot4"
bind 5 "slot5"
bind 6 "slot6"
bind 7 "slot7"
bind 8 "slot8"
bind 9 "slot9"
bind = "yb menu"
bind [ "invprev"
bind ] "invnext"
bind a "+moveleft"
bind b "buy"
bind c "radio3"
bind d "+moveright"
bind e "+use"
bind f "impulse 100"
bind g "drop"
bind h "+commandmenu"
bind k "+voicerecord"
bind m "chooseteam"
bind n "nightvision"
bind o "buyequip"
bind r "+reload"
bind s "+back"
bind t "impulse 201"
bind u "messagemode2"
bind w "+forward"
bind x "radio2"
bind y "messagemode"
bind z "radio1"
bind LEFTARROW "+left"
bind RIGHTARROW "+right"
bind ALT "+strafe"
bind CTRL "+duck"
bind SHIFT "+speed"
bind F1 "autobuy"
bind F2 "rebuy"
bind F3 "menu_loadgame"
bind F4 "menu_controls"
bind F5 "menu_creategame"
bind F6 "savequick"
bind F7 "loadquick"
bind F8 "stop"
bind F10 "menu_main"
bind F12 "snapshot"
bind DEL "+lookdown"
bind PGDN "+lookup"
bind END "centerview"
bind KP_END "centerview"
bind KP_PGDN "+lookup"
bind KP_DEL "+lookdown"
bind BACK "pause"
bind START "cancelselect"
bind DPAD_DOWN "lastinv"
bind MOUSE1 "+attack"
bind MOUSE2 "+attack2"
bind PAUSE "pause"
bind "-" "toggleconsole"
MP3Volume "1.0"
_ah "0"
_cl_autowepswitch "1"
_extended_menus "1"
_vgui_menus "0"
allow_levelshots "0"
ambient_fade "1000"
ambient_level "0.3"
bottomcolor "0"
brightness "0.0"
buymenu_stayon "0"
checkscoreboard "1"
cl_advertise_engine_in_name "1"
cl_allowdownload "1"
cl_allowupload "1"
cl_backspeed "400"
cl_bmodelinterp "1"
cl_bob "0.01"
cl_charset "utf-8"
cl_clockreset "0.1"
cl_cmdbackup "10"
cl_cmdrate "30"
cl_corpsestay "600"
cl_crosshair_color "50 250 50"
cl_crosshair_size "auto"
cl_crosshair_translucent "1"
cl_dlmax "0"
cl_download_ingame "1"
cl_dynamiccrosshair "1"
cl_envshot_size "256"
cl_fancy_nvg "0"
cl_filterstuffcmd "1"
cl_fixtimerate "7.5"
cl_forwardspeed "400"
cl_gunsmoke "0"
cl_hide_motd "0"
cl_himodels "1"
cl_laddermode "2"
cl_lc "1"
cl_lightstyle_lerping "0"
cl_logocolor "orange"
cl_logoext "bmp"
cl_logofile "lambda"
cl_logomaxdim "96"
cl_lw "1"
cl_min_ct "2"
cl_min_t "1"
cl_minmodels "0"
cl_nopred "0"
cl_nosmooth "0"
cl_quakeguns "0"
cl_radartype "0"
cl_righthand "1"
cl_shadows "1"
cl_showerror "0"
cl_showevents "0"
cl_showfps "0"
cl_showpacketloss "0"
cl_showpos "0"
cl_sidespeed "400"
cl_smoothtime "0.1"
cl_test_bandwidth "1"
cl_ticket_generator "revemu2013"
cl_trace_consistency "0"
cl_trace_events "0"
cl_trace_messages "0"
cl_trace_stufftext "0"
cl_updaterate "20"
cl_upmax "508"
cl_vsmoothing "0.05"
cl_weapon_sparks "1"
cl_weapon_wallpuff "1"
cl_weaponlag "0"
cl_weather "1"
cmd_scripting "1"
con_charset "cp1251"
con_color "240 180 24"
con_fontnum "-1"
con_fontrender "2"
con_fontscale "1.0"
con_fontsize "1"
con_mapfilter "1"
con_notifytime "3"
crosshair "1"
dsp_coeff_table "0"
dsp_off "0"
ex_interp "0.1"
fastsprites "0"
fps_max "72"
fs_mount_addon "0"
fs_mount_hd "0"
fs_mount_l10n "0"
fs_mount_lv "0"
gamma "2.5"
gl_clear "0"
gl_vsync "1"
host_allow_materials "0"
hpk_custom_file "custom.hpk"
hpk_max_size "64"
http_autoremove "1"
http_maxconnections "2"
http_show_headers "0"
http_timeout "45"
http_useragent ""
hud_centerid "0"
hud_color "255 160 0"
hud_colored "0"
hud_deathnotice_time "6"
hud_draw "1"
hud_fastswitch "0"
hud_fontrender "0"
hud_fontscale "1.0"
hud_scale "2"
hud_scale_minimal_width "640"
hud_textmode "0"
hud_utf8 "1"
joy_axis_binding "sfpyrl"
joy_enable "1"
joy_forward "1.0"
joy_forward_deadzone "4096"
joy_forward_key_threshold "24576"
joy_lt_threshold "16384"
joy_pitch "100.0"
joy_pitch_deadzone "4096"
joy_rt_threshold "16384"
joy_side "1.0"
joy_side_deadzone "4096"
joy_side_key_threshold "24576"
joy_yaw "100.0"
joy_yaw_deadzone "4096"
joystick "1"
key_rotate "0"
lastdemo ""
look_filter "0"
lookspring "0"
lookstrafe "0"
m_forward "1"
m_ignore "0"
m_pitch "0.022"
m_rawinput "1"
m_side "0.8"
m_yaw "0.022"
menu_bg_fill "0"
menu_mp_firsttime2 "1"
model ""
mp_decals "300"
name "Player"
net_graph "0"
net_graphheight "64"
net_graphpos "1"
net_graphsolid "1"
net_graphwidth "192"
net_scale "5"
net_speeds "0"
numericalmenu "1"
numericalmenu_clientonly "1"
osk_enable "0"
r_adjust_fov "1"
r_decals "4096"
r_dynamic "1"
r_lighting_modulate "0.6"
r_showtree "0"
r_speeds "0"
r_sprite_lerping "1"
r_sprite_lighting "1"
r_studiocache "1"
rate "25000"
room_hires "2"
room_off "0"
s_combine_sounds "0"
s_lerping "0"
s_samplecount "0"
s_show "0"
s_warn_late_precache "0"
scoreboard_showhealth "1"
scoreboard_showmoney "1"
scr_conspeed "600"
scr_drawversion "1"
sensitivity "3"
sleeptime "1"
snd_mute_losefocus "1"
suitvolume "0.25"
sv_aim "1"
sv_allow_PhysX "1"
sv_allow_autoaim "0"
sv_allow_joystick "1"
sv_allow_mouse "1"
sv_allow_noinputdevices "1"
sv_allow_testpacket "1"
sv_allow_touch "1"
sv_allow_vr "1"
sv_autosave "1"
sv_background_freeze "1"
sv_check_errors "0"
sv_contact ""
sv_enttools_enable "0"
sv_enttools_maxfire "5"
sv_expose_player_list "1"
sv_fullupdate_penalty_time "1"
sv_log_onefile "0"
sv_log_outofband "0"
sv_log_singleplayer "0"
sv_master_response_timeout "4"
sv_maxupdaterate "60.0"
sv_minupdaterate "25.0"
sv_precache_meshes "1"
sv_rollangle "0"
sv_speedhack_kick "10"
sv_userinfo_enable_penalty "1"
sv_userinfo_penalty_attempts "4"
sv_userinfo_penalty_multiplier "2"
sv_userinfo_penalty_time "0.3"
sv_voiceenable "1"
sv_voicequality "3"
teammenu_showscores "0"
topcolor "0"
touch_config_file "touch.cfg"
touch_enable "0"
ui_borderclip "0"
ui_language "english"
ui_renderworld "0"
ui_show_window_stack "0"
ui_showmodels "0"
vgui_utf8 "0"
vibration_enable "1"
vibration_length "1.0"
viewsize "120"
voice_avggain "0.5"
voice_enable "0"
voice_maxgain "5.0"
voice_modenable "1"
voice_scale "1.0"
voice_transmit_scale "1.0"
volume "0.7"
xhair_additive "0"
xhair_color "0 255 0 255"
xhair_dot "1"
xhair_dynamic_move "1"
xhair_dynamic_scale "0"
xhair_enable "0"
xhair_gap "0"
xhair_gap_useweaponvalue "0"
xhair_pad "0"
xhair_size "4"
xhair_t "0"
xhair_thick "0"`
